# Generated by Django 5.2.8 on 2025-12-03 05:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
